name: CI
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ["1.19", "1.20"]

    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Format
        run: diff -u <(echo -n) <(gofmt -d .)

      - name: Test
        run: go test -v ./...

      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...
